name: Neovim test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        PROFILE: [.profile]
        VIM: [neovim]
        NEOVIM_TAG: [latest, v0.3.0, v0.4.0, v0.4.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        shell: bash
        run: |
          docker --version
          make VIM=${{ matrix.VIM }} TAG=${{ matrix.NEOVIM_TAG }} image

      - name: Run tests
        shell: bash
        run: |
          make VIM=${{ matrix.VIM }} TAG=${{ matrix.NEOVIM_TAG }} ARGS="-e PROFILE=${{ matrix.PROFILE }} -e CI=docker" test
          make VIM=${{ matrix.VIM }} TAG=${{ matrix.NEOVIM_TAG }} helptags
