name: Vim test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        PROFILE: [.profile]
        VIM: [vim]
        VIM_TAG: [latest, v8.0.0107, v8.1.0000, v8.1.2000]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        shell: bash
        run: |
          docker --version
          make VIM=${{ matrix.VIM }} TAG=${{ matrix.VIM_TAG }} image

      - name: Run tests
        shell: bash
        run: |
          make VIM=${{ matrix.VIM }} TAG=${{ matrix.VIM_TAG }} ARGS="-e PROFILE=${{ matrix.PROFILE }} -e CI=docker" test
          make VIM=${{ matrix.VIM }} TAG=${{ matrix.VIM_TAG }} helptags
